version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: oxymore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: oxymore
      MYSQL_USER: oxymore
      MYSQL_PASSWORD: oxymore123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis
  redis:
    image: redis:7-alpine
    container_name: oxymore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: oxymore-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: oxymore
      DB_USER: oxymore
      DB_PASSWORD: oxymore123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      timeout: 20s
      retries: 10
      start_period: 30s

  # Admin Panel
  admin:
    build:
      context: .
      dockerfile: apps/oxymore-admin/Dockerfile
    container_name: oxymore-admin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      timeout: 20s
      retries: 10
      start_period: 30s

  # Main App
  app:
    build:
      context: .
      dockerfile: apps/oxymore-app/Dockerfile
    container_name: oxymore-app
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      timeout: 20s
      retries: 10
      start_period: 30s

  # Marketing Site
  site:
    build:
      context: .
      dockerfile: apps/oxymore-site/Dockerfile
    container_name: oxymore-site
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - oxymore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      timeout: 20s
      retries: 10
      start_period: 30s

  # Redis Commander (Optional - for debugging)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: oxymore-redis-commander
    restart: unless-stopped
    ports:
      - "8083:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - oxymore-network

volumes:
  mysql_data:
  redis_data:

networks:
  oxymore-network:
    driver: bridge
