import { Express } from "express";
import userRoutes from "./routes/user/user";
import notificationRoutes from "./routes/notification/notification";
import channelBotRoutes from "./routes/messaging/channelBot";
import privateMessageRoutes from "./routes/messaging/privateMessage";
import authRoutes from "./routes/user/auth";
import roleRoutes from "./routes/admin/role";
import notificationAdminRoutes from "./routes/admin/notificationAdmin";

import messageBotRoutes from "./routes/messaging/messageBot";
import userVideoRoutes from "./routes/user/userVideo";
import videoCommentRoutes from "./routes/content/videoComment";
import videoLikeRoutes from "./routes/content/videoLike";
import notificationReadRoutes from "./routes/notification/notificationRead";
import firstPagePromotionVideoRoutes from "./routes/content/firstPagePromotionVideo";
import badgeRoutes from "./routes/badge/badge";
import userBadgeRoutes from "./routes/user/userBadge";
import userFollowingRoutes from "./routes/user/userFollowing";
import userSanctionRoutes from "./routes/user/userSanction";
import groupRoutes from "./routes/group/group";
import groupMemberRoutes from "./routes/group/groupMember";
import friendRoutes from "./routes/user/friend";
import leagueRoutes from "./routes/league/league";
import leagueTeamRoutes from "./routes/league/leagueTeam";
import mapRoutes from "./routes/game/map";
import mapPickbanRoutes from "./routes/game/mapPickban";
import matchRoutes from "./routes/match/match";
import matchChatRoutes from "./routes/match/matchChat";
import matchMapRoutes from "./routes/match/matchMap";
import pinnedMessageTeamRoutes from "./routes/pinnedMessage/pinnedMessageTeam";
import roomRoutes from "./routes/room/room";
import shopItemRoutes from "./routes/shop/shopItem";
import teamRoutes from "./routes/team/team";
import teamChatRoutes from "./routes/team/teamChat";
import teamChatReportRoutes from "./routes/team/teamChatReport";
import teamMemberRoutes from "./routes/team/teamMember";
import teamSubscriptionRoutes from "./routes/team/teamSubscription";
import teamApplicationRoutes from "./routes/team/teamApplication";
import teamChallengeRoutes from "./routes/team/teamChallenge";
import tournamentRoutes from "./routes/tournament/tournament";
import tournamentTeamRoutes from "./routes/tournament/tournamentTeam";
import tournamentMapRoutes from "./routes/tournament/tournamentMap";
import kanbanRoutes from "./routes/kanban/kanban";
import calendarRoutes from "./routes/calendar/calendar";
import gameRoutes from "./routes/game/game";

export const registerRoutes = (app: Express) => {
  // Routes publiques
  app.use("/api/auth", authRoutes);
  app.use("/api/users", userRoutes);
  app.use("/api/roles", roleRoutes);
  app.use("/api/notifications", notificationRoutes);
  app.use("/api/admin/notifications", notificationAdminRoutes);
  app.use("/api/channel-bots", channelBotRoutes);
  app.use("/api/private-messages", privateMessageRoutes);
  app.use("/api/message-bots", messageBotRoutes);
  app.use("/api/user-videos", userVideoRoutes);
  app.use("/api/video-comments", videoCommentRoutes);
  app.use("/api/video-likes", videoLikeRoutes);
  app.use("/api/notification-reads", notificationReadRoutes);
  app.use("/api/first-page-promotion-videos", firstPagePromotionVideoRoutes);
  app.use("/api/badges", badgeRoutes);
  app.use("/api/user-badges", userBadgeRoutes);
  app.use("/api/user-followings", userFollowingRoutes);
  app.use("/api/user-sanctions", userSanctionRoutes);
  app.use("/api/groups", groupRoutes);
  app.use("/api/group-members", groupMemberRoutes);
  app.use("/api/friends", friendRoutes);
  app.use("/api/leagues", leagueRoutes);
  app.use("/api/league-teams", leagueTeamRoutes);
  app.use("/api/maps", mapRoutes);
  app.use("/api/map-pickbans", mapPickbanRoutes);
  app.use("/api/matches", matchRoutes);
  app.use("/api/match-chats", matchChatRoutes);
  app.use("/api/match-maps", matchMapRoutes);
  app.use("/api/pinned-message-teams", pinnedMessageTeamRoutes);
  app.use("/api/rooms", roomRoutes);
  app.use("/api/shop-items", shopItemRoutes);
  app.use("/api/teams", teamRoutes);
  app.use("/api/team-chats", teamChatRoutes);
  app.use("/api/team-chat-reports", teamChatReportRoutes);
  app.use("/api/team-members", teamMemberRoutes);
  app.use("/api/team-subscriptions", teamSubscriptionRoutes);
  app.use("/api/team-applications", teamApplicationRoutes);
  app.use("/api/team-challenges", teamChallengeRoutes);
  app.use("/api/tournaments", tournamentRoutes);
  app.use("/api/tournament-teams", tournamentTeamRoutes);
  app.use("/api/tournament-maps", tournamentMapRoutes);
  app.use("/api/kanban", kanbanRoutes);
  app.use("/api/calendar", calendarRoutes);
  app.use("/api/games", gameRoutes);
};
