import { Express } from "express";
import userRoutes from "./routes/user";
import notificationRoutes from "./routes/notification";
import channelBotRoutes from "./routes/channelBot";
import authRoutes from "./routes/auth";
import roleRoutes from "./routes/role";

import messageBotRoutes from "./routes/messageBot";
import userVideoRoutes from "./routes/userVideo";
import videoCommentRoutes from "./routes/videoComment";
import videoLikeRoutes from "./routes/videoLike";
import notificationReadRoutes from "./routes/notificationRead";
import firstPagePromotionVideoRoutes from "./routes/firstPagePromotionVideo";
import badgeRoutes from "./routes/badge";
import userBadgeRoutes from "./routes/userBadge";
import userFollowingRoutes from "./routes/userFollowing";
import userSanctionRoutes from "./routes/userSanction";
import groupRoutes from "./routes/group";
import groupMemberRoutes from "./routes/groupMember";
import friendRoutes from "./routes/friend";
import leagueRoutes from "./routes/league";
import leagueTeamRoutes from "./routes/leagueTeam";
import mapRoutes from "./routes/map";
import mapPickbanRoutes from "./routes/mapPickban";
import matchRoutes from "./routes/match";
import matchChatRoutes from "./routes/matchChat";
import matchMapRoutes from "./routes/matchMap";
import pinnedMessageTeamRoutes from "./routes/pinnedMessageTeam";
import roomRoutes from "./routes/room";
import shopItemRoutes from "./routes/shopItem";
import teamRoutes from "./routes/team";
import teamChatRoutes from "./routes/teamChat";
import teamMemberRoutes from "./routes/teamMember";
import teamSubscriptionRoutes from "./routes/teamSubscription";
import tournamentRoutes from "./routes/tournament";
import tournamentTeamRoutes from "./routes/tournamentTeam";
import tournamentMapRoutes from "./routes/tournamentMap";
import kanbanRoutes from "./routes/kanban";
import calendarRoutes from "./routes/calendar";
import gameRoutes from "./routes/game";

export const registerRoutes = (app: Express) => {
  // Routes publiques
  app.use("/api/auth", authRoutes);
  app.use("/api/users", userRoutes);
  app.use("/api/roles", roleRoutes);
  app.use("/api/notifications", notificationRoutes);
  app.use("/api/channel-bots", channelBotRoutes);
  app.use("/api/message-bots", messageBotRoutes);
  app.use("/api/user-videos", userVideoRoutes);
  app.use("/api/video-comments", videoCommentRoutes);
  app.use("/api/video-likes", videoLikeRoutes);
  app.use("/api/notification-reads", notificationReadRoutes);
  app.use("/api/first-page-promotion-videos", firstPagePromotionVideoRoutes);
  app.use("/api/badges", badgeRoutes);
  app.use("/api/user-badges", userBadgeRoutes);
  app.use("/api/user-followings", userFollowingRoutes);
  app.use("/api/user-sanctions", userSanctionRoutes);
  app.use("/api/groups", groupRoutes);
  app.use("/api/group-members", groupMemberRoutes);
  app.use("/api/friends", friendRoutes);
  app.use("/api/leagues", leagueRoutes);
  app.use("/api/league-teams", leagueTeamRoutes);
  app.use("/api/maps", mapRoutes);
  app.use("/api/map-pickbans", mapPickbanRoutes);
  app.use("/api/matches", matchRoutes);
  app.use("/api/match-chats", matchChatRoutes);
  app.use("/api/match-maps", matchMapRoutes);
  app.use("/api/pinned-message-teams", pinnedMessageTeamRoutes);
  app.use("/api/rooms", roomRoutes);
  app.use("/api/shop-items", shopItemRoutes);
  app.use("/api/teams", teamRoutes);
  app.use("/api/team-chats", teamChatRoutes);
  app.use("/api/team-members", teamMemberRoutes);
  app.use("/api/team-subscriptions", teamSubscriptionRoutes);
  app.use("/api/tournaments", tournamentRoutes);
  app.use("/api/tournament-teams", tournamentTeamRoutes);
  app.use("/api/tournament-maps", tournamentMapRoutes);
  app.use("/api/kanban", kanbanRoutes);
  app.use("/api/calendar", calendarRoutes);
  app.use("/api/games", gameRoutes);
};
